// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: all.sql

package database

import (
	"context"
)

const delete = `-- name: Delete :exec
TRUNCATE feeds
`

func (q *Queries) Delete(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, delete)
	return err
}
